name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
      runs-on: ubuntu-22.04-arm
      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            sudo apt-get update  > /dev/null 2>&1
            sudo apt-get install -y libcurl4-openssl-dev libgcrypt20-dev libev-dev  libaio-dev libssl-dev cmake wget make g++ > /dev/null 2>&1

        - name: Download sources
          run: |
            sudo wget -q  https://downloads.percona.com/downloads/Percona-XtraBackup-2.4/Percona-XtraBackup-2.4.29/source/tarball/percona-xtrabackup-2.4.29.tar.gz 
            sudo wget -q https://nchc.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz

        - name: Build
          run: |
            tar xzf percona-xtrabackup-2.4.29.tar.gz 
            tar xzf boost_1_59_0.tar.gz
            cd percona-xtrabackup-2.4.29
            mkdir -p build 
            cd build
            cmake ..  -DDOWNLOAD_BOOST=OFF -DWITH_BOOST=/home/runner/work/percona-xtrabackup-2.4.29-arm64/percona-xtrabackup-2.4.29-arm64/boost_1_59_0.tar.gz -DBUILD_CONFIG=xtrabackup_release
            make -j$(nproc)
            sudo make install

        - name: pack percona-xtrabackup
          run: |
            sudo cp -r /usr/local/xtrabackup percona-xtrabackup-2.4.29-arm64
            sudo tar czvf percona-xtrabackup-2.4.29-arm64.tar.gz percona-xtrabackup-2.4.29-arm64

        - name:  Create Release
          uses: softprops/action-gh-release@v1
          with:
            files: percona-xtrabackup-2.4.29-arm64.tar.gz
            tag_name: v2.4.29
            release_name: Percona XtraBackup 2.4.29 arm64
            body: |
              This is the release of Percona XtraBackup 2.4.29 arm64
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}



